In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
data=pd.read_csv('D:\datatrained\project week 1\mushroom.csv')

In [7]:
data

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0       p         x           s         n       t    p               f   
1       e         x           s         y       t    a               f   
2       e         b           s         w       t    l               f   
3       p         x           y         w       t    p               f   
4       e         x           s         g       f    n               f   
...   ...       ...         ...       ...     ...  ...             ...   
8119    e         k           s         n       f    n               a   
8120    e         x           s         n       f    n               a   
8121    e         f           s         n       f    n               a   
8122    p         k           y         n       f    y               f   
8123    e         x           s         n       f    n               a   

     gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring_number ring_type spore_print_color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [10]:
data.isnull().sum()

type                        0
cap_shape                   0
cap_surface                 0
cap_color                   0
bruises                     0
odor                        0
gill_attachment             0
gill_spacing                0
gill_size                   0
gill_color                  0
stalk_shape                 0
stalk_root                  0
stalk_surface_above_ring    0
stalk_surface_below_ring    0
stalk_color_above_ring      0
stalk_color_below_ring      0
veil_type                   0
veil_color                  0
ring_number                 0
ring_type                   0
spore_print_color           0
population                  0
habitat                     0
dtype: int64

In [12]:
data.dtypes

type                        object
cap_shape                   object
cap_surface                 object
cap_color                   object
bruises                     object
odor                        object
gill_attachment             object
gill_spacing                object
gill_size                   object
gill_color                  object
stalk_shape                 object
stalk_root                  object
stalk_surface_above_ring    object
stalk_surface_below_ring    object
stalk_color_above_ring      object
stalk_color_below_ring      object
veil_type                   object
veil_color                  object
ring_number                 object
ring_type                   object
spore_print_color           object
population                  object
habitat                     object
dtype: object

In [13]:
data.keys()

Index(['type', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'stalk_surface_above_ring',
       'stalk_surface_below_ring', 'stalk_color_above_ring',
       'stalk_color_below_ring', 'veil_type', 'veil_color', 'ring_number',
       'ring_type', 'spore_print_color', 'population', 'habitat'],
      dtype='object')

In [14]:
list=['type', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
       'gill_attachment', 'gill_spacing', 'gill_size', 'gill_color',
       'stalk_shape', 'stalk_root', 'stalk_surface_above_ring',
       'stalk_surface_below_ring', 'stalk_color_above_ring',
       'stalk_color_below_ring', 'veil_type', 'veil_color', 'ring_number',
       'ring_type', 'spore_print_color', 'population', 'habitat']

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for val in list:
    data[val]=le.fit_transform(data[val].astype(str))

In [20]:
data

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0        1          5            2          4        1     6                1   
1        0          5            2          9        1     0                1   
2        0          0            2          8        1     3                1   
3        1          5            3          8        1     6                1   
4        0          5            2          3        0     5                1   
...    ...        ...          ...        ...      ...   ...              ...   
8119     0          3            2          4        0     5                0   
8120     0          5            2          4        0     5                0   
8121     0          2            2          4        0     5                0   
8122     1          3            3          4        0     8                1   
8123     0          5            2          4        0     5                0   

      gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0                0          1           4  ...                         2   
1                0          0           4  ...                         2   
2                0          0           5  ...                         2   
3                0          1           5  ...                         2   
4                1          0           4  ...                         2   
...            ...        ...         ...  ...                       ...   
8119             0          0          11  ...                         2   
8120             0          0          11  ...                         2   
8121             0          0           5  ...                         2   
8122             0          1           0  ...                         1   
8123             0          0          11  ...                         2   

      stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                          7                       7          0           2   
1                          7                       7          0           2   
2                          7                       7          0           2   
3                          7                       7          0           2   
4                          7                       7          0           2   
...                      ...                     ...        ...         ...   
8119                       5                       5          0           1   
8120                       5                       5          0           0   
8121                       5                       5          0           1   
8122                       7                       7          0           2   
8123                       5                       5          0           1   

      ring_number  ring_type  spore_print_color  population  habitat  
0               1          4                  2           3        5  
1               1          4                  3           2        1  
2               1          4                  3           2        3  
3               1          4                  2           3        5  
4               1          0                  3           0        1  
...           ...        ...                ...         ...      ...  
8119            1          4                  0           1        2  
8120            1          4                  0           4        2  
8121            1          4                  0           1        2  
8122            1          0                  7           4        2  
8123            1          4                  4           1        2  

[8124 rows x 23 columns]

In [23]:
x=data.iloc[:,0:22]
x

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0        1          5            2          4        1     6                1   
1        0          5            2          9        1     0                1   
2        0          0            2          8        1     3                1   
3        1          5            3          8        1     6                1   
4        0          5            2          3        0     5                1   
...    ...        ...          ...        ...      ...   ...              ...   
8119     0          3            2          4        0     5                0   
8120     0          5            2          4        0     5                0   
8121     0          2            2          4        0     5                0   
8122     1          3            3          4        0     8                1   
8123     0          5            2          4        0     5                0   

      gill_spacing  gill_size  gill_color  ...  stalk_surface_above_ring  \
0                0          1           4  ...                         2   
1                0          0           4  ...                         2   
2                0          0           5  ...                         2   
3                0          1           5  ...                         2   
4                1          0           4  ...                         2   
...            ...        ...         ...  ...                       ...   
8119             0          0          11  ...                         2   
8120             0          0          11  ...                         2   
8121             0          0           5  ...                         2   
8122             0          1           0  ...                         2   
8123             0          0          11  ...                         2   

      stalk_surface_below_ring  stalk_color_above_ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk_color_below_ring  veil_type  veil_color  ring_number  ring_type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore_print_color  population  
0                     2           3  
1                     3           2  
2                     3           2  
3                     2           3  
4                     3           0  
...                 ...         ...  
8119                  0           1  
8120                  0           4  
8121                  0           1  
8122                  7           4  
8123                  4           1  

[8124 rows x 22 c

In [24]:
y=data.iloc[:,-1]
y

0       5
1       1
2       3
3       5
4       1
       ..
8119    2
8120    2
8121    2
8122    2
8123    2
Name: habitat, Length: 8124, dtype: int32

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.80,random_state=42)


In [52]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.554923076923077
[[1712  312  322    0  168    0    0]
 [ 332 1004   34  246    0  104    0]
 [ 184   17  313    0  156    0    0]
 [  25   27    0  181    0    0    0]
 [ 205  201  303   67  146    4    0]
 [ 146   40    0    0    0  109    0]
 [   0    0    0    0    0    0  142]]
              precision    recall  f1-score   support

           0       0.66      0.68      0.67      2514
           1       0.63      0.58      0.60      1720
           2       0.32      0.47      0.38       670
           3       0.37      0.78      0.50       233
           4       0.31      0.16      0.21       926
           5       0.50      0.37      0.43       295
           6       1.00      1.00      1.00       142

    accuracy                           0.55      6500
   macro avg       0.54      0.58      0.54      6500
weighted avg       0.56      0.55      0.55      6500



In [53]:
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=mnb.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.554923076923077
[[1712  312  322    0  168    0    0]
 [ 332 1004   34  246    0  104    0]
 [ 184   17  313    0  156    0    0]
 [  25   27    0  181    0    0    0]
 [ 205  201  303   67  146    4    0]
 [ 146   40    0    0    0  109    0]
 [   0    0    0    0    0    0  142]]
              precision    recall  f1-score   support

           0       0.66      0.68      0.67      2514
           1       0.63      0.58      0.60      1720
           2       0.32      0.47      0.38       670
           3       0.37      0.78      0.50       233
           4       0.31      0.16      0.21       926
           5       0.50      0.37      0.43       295
           6       1.00      1.00      1.00       142

    accuracy                           0.55      6500
   macro avg       0.54      0.58      0.54      6500
weighted avg       0.56      0.55      0.55      6500



In [54]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
svc.score(x_train,y_train)
preddtc=mnb.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.554923076923077
[[1712  312  322    0  168    0    0]
 [ 332 1004   34  246    0  104    0]
 [ 184   17  313    0  156    0    0]
 [  25   27    0  181    0    0    0]
 [ 205  201  303   67  146    4    0]
 [ 146   40    0    0    0  109    0]
 [   0    0    0    0    0    0  142]]
              precision    recall  f1-score   support

           0       0.66      0.68      0.67      2514
           1       0.63      0.58      0.60      1720
           2       0.32      0.47      0.38       670
           3       0.37      0.78      0.50       233
           4       0.31      0.16      0.21       926
           5       0.50      0.37      0.43       295
           6       1.00      1.00      1.00       142

    accuracy                           0.55      6500
   macro avg       0.54      0.58      0.54      6500
weighted avg       0.56      0.55      0.55      6500



In [55]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
predknn=mnb.predict(x_test)
print(accuracy_score(y_test,predknn))
print(confusion_matrix(y_test,predknn))
print(classification_report(y_test,predknn))

0.554923076923077
[[1712  312  322    0  168    0    0]
 [ 332 1004   34  246    0  104    0]
 [ 184   17  313    0  156    0    0]
 [  25   27    0  181    0    0    0]
 [ 205  201  303   67  146    4    0]
 [ 146   40    0    0    0  109    0]
 [   0    0    0    0    0    0  142]]
              precision    recall  f1-score   support

           0       0.66      0.68      0.67      2514
           1       0.63      0.58      0.60      1720
           2       0.32      0.47      0.38       670
           3       0.37      0.78      0.50       233
           4       0.31      0.16      0.21       926
           5       0.50      0.37      0.43       295
           6       1.00      1.00      1.00       142

    accuracy                           0.55      6500
   macro avg       0.54      0.58      0.54      6500
weighted avg       0.56      0.55      0.55      6500

